// <auto-generated />
using System;
using CleanArc.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CleanArc.Context.Migrations
{
    [DbContext(typeof(CleanArchDBContext))]
    partial class CleanArchDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CleanArch.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 940, DateTimeKind.Local).AddTicks(5467),
                            Name = "Product 1",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 2,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9437),
                            Name = "Product 2",
                            Price = 2000.0
                        },
                        new
                        {
                            Id = 3,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9483),
                            Name = "Product 3",
                            Price = 3000.0
                        },
                        new
                        {
                            Id = 4,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9487),
                            Name = "Product 4",
                            Price = 4000.0
                        },
                        new
                        {
                            Id = 5,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9489),
                            Name = "Product 5",
                            Price = 5000.0
                        },
                        new
                        {
                            Id = 6,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9490),
                            Name = "Product 6",
                            Price = 6000.0
                        },
                        new
                        {
                            Id = 7,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9492),
                            Name = "Product 7",
                            Price = 7000.0
                        },
                        new
                        {
                            Id = 8,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9494),
                            Name = "Product 8",
                            Price = 8000.0
                        },
                        new
                        {
                            Id = 9,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9496),
                            Name = "Product 9",
                            Price = 9000.0
                        },
                        new
                        {
                            Id = 10,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9498),
                            Name = "Product 10",
                            Price = 10000.0
                        },
                        new
                        {
                            Id = 11,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9500),
                            Name = "Product 11",
                            Price = 11000.0
                        },
                        new
                        {
                            Id = 12,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9502),
                            Name = "Product 12    ",
                            Price = 12000.0
                        },
                        new
                        {
                            Id = 13,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9504),
                            Name = "Product 13",
                            Price = 13000.0
                        },
                        new
                        {
                            Id = 14,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9506),
                            Name = "Product 14",
                            Price = 14000.0
                        },
                        new
                        {
                            Id = 15,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9508),
                            Name = "Product 15",
                            Price = 15000.0
                        },
                        new
                        {
                            Id = 16,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9510),
                            Name = "Product 16",
                            Price = 16000.0
                        },
                        new
                        {
                            Id = 17,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9512),
                            Name = "Product 17",
                            Price = 17000.0
                        },
                        new
                        {
                            Id = 18,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9514),
                            Name = "Product 18",
                            Price = 18000.0
                        },
                        new
                        {
                            Id = 19,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9516),
                            Name = "Product 19",
                            Price = 19000.0
                        },
                        new
                        {
                            Id = 20,
                            LastUpdate = new DateTime(2020, 12, 12, 13, 52, 34, 941, DateTimeKind.Local).AddTicks(9518),
                            Name = "Product 20",
                            Price = 20000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
